#!/usr/bin/env node
/**
 * Agentic SDLC Pipeline Setup Script
 * 
 * Interactive setup to configure the pipeline
 * 
 * Usage: npm run agents:setup
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ENV_EXAMPLE_PATH = path.join(__dirname, '..', '.env.example');
const ENV_PATH = path.join(__dirname, '..', '.env');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer);
    });
  });
}

function log(message) {
  console.log(message);
}

function logSuccess(message) {
  console.log(`✅ ${message}`);
}

function logError(message) {
  console.log(`❌ ${message}`);
}

function logInfo(message) {
  console.log(`ℹ️  ${message}`);
}

async function main() {
  log('\n🚀 Agentic SDLC Pipeline Setup\n');
  log('='.repeat(50));

  // Check if .env already exists
  if (fs.existsSync(ENV_PATH)) {
    logInfo('.env file already exists.');
    const overwrite = await question('Do you want to overwrite it? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      log('Skipping .env creation.');
    } else {
      await createEnvFile();
    }
  } else {
    await createEnvFile();
  }

  // Verify GitHub token
  log('\n🔑 GitHub Token Verification');
  log('-'.repeat(50));
  logInfo('Your GitHub token should have these scopes:');
  log('   - repo (Full control of private repositories)');
  log('   - workflow (Update GitHub Actions workflows)');
  log('\nCreate a token at: https://github.com/settings/tokens');

  // Install dependencies check
  log('\n📦 Dependencies Check');
  log('-'.repeat(50));
  const requiredDeps = ['@octokit/rest', 'commander', 'ts-node'];
  const packageJson = JSON.parse(
    fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf-8')
  );

  let missingDeps = [];
  for (const dep of requiredDeps) {
    const isInDeps =
      packageJson.dependencies?.[dep] || packageJson.devDependencies?.[dep];
    if (!isInDeps) {
      missingDeps.push(dep);
    } else {
      logSuccess(`${dep} is installed`);
    }
  }

  if (missingDeps.length > 0) {
    logError(`Missing dependencies: ${missingDeps.join(', ')}`);
    logInfo('Run: npm install');
  } else {
    logSuccess('All required dependencies are installed');
  }

  // GitHub Actions workflow check
  log('\n⚙️  GitHub Actions Workflow');
  log('-'.repeat(50));
  const workflowPath = path.join(
    __dirname,
    '..',
    '.github',
    'workflows',
    'agents-pipeline.yml'
  );
  if (fs.existsSync(workflowPath)) {
    logSuccess('GitHub Actions workflow is configured');
  } else {
    logError('GitHub Actions workflow not found');
    logInfo('Make sure .github/workflows/agents-pipeline.yml exists');
  }

  // Final instructions
  log('\n🎉 Setup Complete!');
  log('='.repeat(50));
  log('\nNext steps:');
  log('1. Add the backlog-item label to your GitHub Issues');
  log('2. Run: npm run agents:process');
  log('3. Or wait for the automated hourly run');
  log('\nUseful commands:');
  log('   npm run agents:process      - Process all ready items');
  log('   npm run agents:issue -- --issue=123  - Process specific issue');
  log('   npm run agents:watch        - Continuous processing');
  log('   npm run agents:process -- --dry-run  - Simulate without changes');
  log('\n' + '='.repeat(50) + '\n');

  rl.close();
}

async function createEnvFile() {
  log('\n📝 Creating .env file\n');

  const token = await question('GitHub Token (ghp_...): ');
  const owner = await question('GitHub Username/Org: ');
  const repo = await question('Repository Name (trapp): ');

  const envContent = `# Agentic SDLC Pipeline Configuration
# Generated by setup script

GITHUB_TOKEN=${token}
GITHUB_REPO_OWNER=${owner}
GITHUB_REPO_NAME=${repo || 'trapp'}

# Optional settings (uncomment to customize)
# AGENT_TIMEOUT=300000
# APPROVAL_TIMEOUT=86400000
# POLL_INTERVAL=300000
# VERBOSE=true
`;

  fs.writeFileSync(ENV_PATH, envContent);
  logSuccess('.env file created');

  // Mask the token in output
  const maskedToken = token.substring(0, 6) + '...' + token.substring(token.length - 4);
  logInfo(`Token configured: ${maskedToken}`);
}

// Run setup
main().catch((error) => {
  logError(`Setup failed: ${error.message}`);
  process.exit(1);
});
